### ISSUE TITLE
Complete general/build/token-standards page

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#109]

**Comment by devBlue4** [comment]
Suggestion: Relocate Token Standards Page
Suggesting to move the Token Standards page to the General/Build section since it applies to both Core and eSpace. This might enhance its accessibility and relevance.

**Comment by darwintree** [comment]
> Suggestion: Relocate Token Standards Page Suggesting to move the Token Standards page to the General/Build section since it applies to both Core and eSpace. This might enhance its accessibility and relevance.

Thank you! Will consider moving the article before we completing it.
