### ISSUE TITLE
FAQ Integration

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#148]
**Describe the feature or improvement 描述新特性或改进**
Integrate https://github.com/conflux-fans/conflux-faqs/blob/main/community-faq.md into general/faq

**Affected page(s) or section(s) 受影响的页面**
general/faq

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
https://github.com/Conflux-Chain/conflux-documentation/pull/231

**Comment by 0xn1c0** [comment]
PR Closed: https://github.com/Conflux-Chain/conflux-documentation/pull/231
