### ISSUE TITLE
Responsive Logo in Dark Mode

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#149]
**Describe the feature or improvement 描述新特性或改进**
Currently the logo of the website is not responsive. It shall change in dark mode

**Affected page(s) or section(s) 受影响的页面**
Any

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
[https://github.com/Conflux-Chain/design-resource-lab/blob/master/0. CONFLUX LOGO/Logo Symbol/no space/Logo Symbol_no space_JPG/Logo Mark/Brand Black.jpg](https://github.com/Conflux-Chain/design-resource-lab/blob/master/0.%20CONFLUX%20LOGO/Logo%20Symbol/no%20space/Logo%20Symbol_no%20space_JPG/Logo%20Mark/Brand%20Black.jpg)

[https://github.com/Conflux-Chain/design-resource-lab/blob/master/0. CONFLUX LOGO/Logo Symbol/no space/Logo Symbol_no space_JPG/Logo Mark/White.jpg](https://github.com/Conflux-Chain/design-resource-lab/blob/master/0.%20CONFLUX%20LOGO/Logo%20Symbol/no%20space/Logo%20Symbol_no%20space_JPG/Logo%20Mark/White.jpg)
