### ISSUE TITLE
Add SDK tutorials for eSpace developers

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#168]
**Describe the feature or improvement 描述新特性或改进**

Add SDK tutorials for eSpace developers

**Affected page(s) or section(s) 受影响的页面**

a new page in espace/build/... page

**Why is this feature or improvement important? 为什么需要这个新特性或改进？**

Though Conflux eSapce is fully compatible with EVM, only EIP-155 transactions are accepted. However, the ethereum SDKs tend to adopt EIP-1559 as the default encoding approach so it still require developers to add extra settings to their code in order to construct legacy transactions

**Optional: Implementation ideas 可选：如何实现**

List how to construct legacy ethereum transactions documents for popular ethererum libraries.

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by Pana** [comment]
Seems only some developer tools need special config or flag for legacy TX, most SDKs will work automatically
