### ISSUE TITLE
Add `ulimit -n 10000` back to Node-Relating Documents

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#181]
**Describe the feature or improvement 描述新特性或改进**
Add `ulimit -n 10000` back to Node Documents

**Affected page(s) or section(s) 受影响的页面**
Node running pages

**Why is this feature or improvement important? 为什么需要这个新特性或改进？**
This sentence is somehow missed during migration

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
Updated.

https://doc.confluxnetwork.org/docs/general/run-a-node/

![image](https://github.com/Conflux-Chain/conflux-documentation/assets/111755752/dc5939a5-0577-4d28-9f3b-62aed826de68)
