### ISSUE TITLE
Improve Glossary Page

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#191]
**Describe the feature or improvement 描述新特性或改进**
Add more contents and check translation for glossary page in Crowdin

**Affected page(s) or section(s) 受影响的页面**
general/../glossary

**Why is this feature or improvement important? 为什么需要这个新特性或改进？**
The glossary page would serve as an index page for those who are not familiar with Conflux. And besides, there is not a universal translation guide for Conflux terms.

- [x] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
I'll take this issue. Now working on a outline of the definitions to be added

**Comment by 0xn1c0** [comment]
PR Submitted -> https://github.com/Conflux-Chain/conflux-documentation/pull/209
