### ISSUE TITLE
Conflux Paywall Tutorial(Confura Api Key)

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#195]
**Describe the feature or improvement 描述新特性或改进**

Add tutorial for how to pay for Confura key

**Affected page(s) or section(s) 受影响的页面**

* a new page in general/tutorials (named `general/tutorials/conflux-paywall` or any other related name)
* add links in network endpoints page(both core and espace)

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by darwintree** [comment]
@wanliqun Could finish the tutorial if you had time

**Comment by wanliqun** [comment]
Paywall is used for payment on both scan and confura, which share the same path to get an Api keys.  Maybe we should collaborate to write a more general tutorial for Paywall instead. @Tigo9527
