### ISSUE TITLE
PoW reward has changed to 1 CFX

### ISSUE THREAD

**Issue by Pana** [Conflux-Chain/conflux-documentation#197]
**Describe the issue 描述问题**
PoW reward has changed to 1 CFX now, these page info need to be update: https://doc.confluxnetwork.org/docs/general/conflux-basics/economics#cfx-annual-inflation

**Comment by darwintree** [comment]
It is mentioned in the article that the PoW reward is subject to change and corresponding info is mentioned in the info block. Will improve writing to make it more clear

<img width="806" alt="image" src="https://github.com/Conflux-Chain/conflux-documentation/assets/17946284/921ec9c2-50c7-429d-ba96-b15215da8738">
