### ISSUE TITLE
add links for okx page 

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#202]
**Describe the feature or improvement 描述新特性或改进**
https://doc.confluxnetwork.org/docs/general/tutorials/transferring-funds/from-exchanges/okx
Links are missing for the page

**Affected page(s) or section(s) 受影响的页面**
Please provide the URL(s) or the section(s) of the documentation where the feature or improvement would be relevant.

**Why is this feature or improvement important? 为什么需要这个新特性或改进？**
Explain why this feature or improvement would benefit the documentation and its users.

**Optional: Implementation ideas 可选：如何实现**
If you have any ideas on how to implement this feature or improvement, please provide them here.

**Optional: Additional context：可选：其他上下文信息**
Add any other context, screenshots, or relevant information about the feature or improvement.

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
@darwintree can you please specify which links are missing please?
