### ISSUE TITLE
Homepage Card Link and Style

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#203]
**Describe the feature or improvement 描述新特性或改进**
![image](https://github.com/Conflux-Chain/conflux-documentation/assets/17946284/a89415a8-5f61-4d5f-bf25-cc0a2a3c7c34)

**Affected page(s) or section(s) 受影响的页面**
Please provide the URL(s) or the section(s) of the documentation where the feature or improvement would be relevant.

**Why is this feature or improvement important? 为什么需要这个新特性或改进？**
Explain why this feature or improvement would benefit the documentation and its users.

**Optional: Implementation ideas 可选：如何实现**
If you have any ideas on how to implement this feature or improvement, please provide them here.

**Optional: Additional context：可选：其他上下文信息**
Add any other context, screenshots, or relevant information about the feature or improvement.

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
It's fixed. https://github.com/Conflux-Chain/conflux-documentation/pull/221
