### ISSUE TITLE
Rewrite Running Node Pages

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#207]
**Describe the feature or improvement 描述新特性或改进**

The running node pages need updating and a lot of important information is missed (for example, the snapshot usage, etc). We should make sure it is possible everyone can start a node through the tutorial.

**Affected page(s) or section(s) 受影响的页面**

General/Run a Node/...

**Why is this feature or improvement important? 为什么需要这个新特性或改进？**
Explain why this feature or improvement would benefit the documentation and its users.

**Optional: Implementation ideas 可选：如何实现**
If you have any ideas on how to implement this feature or improvement, please provide them here.

**Optional: Additional context：可选：其他上下文信息**
Add any other context, screenshots, or relevant information about the feature or improvement.

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
It's done:
https://github.com/Conflux-Chain/conflux-documentation/pull/220
