### ISSUE TITLE
PoS Overview page/ sentence mistake

### ISSUE THREAD

**Issue by devBlue4** [Conflux-Chain/conflux-documentation#233]
**Describe the issue 描述问题**
There is sentence that refers to something that is not on the documentation.
23 "All the times stated below are corresponding to the number of blocks."

**Affected page(s) or section(s) 受影响的页面**
docs/general/conflux-basics/consensus-mechanisms/proof-of-stake/pos_overview.md
23
Just before PoS Account section.

**Optional: Suggested solution 可选：如何解决**
Delete the sentence "All the times stated below are corresponding to the number of **blocks." from line 23.

- [ ] I'd be willing to fix this issue myself. 我将自己修复这个问题。

**Comment by darwintree** [comment]
Thank you for your feedback. What do you mean that "something that is not on the documentation" ?

The sentence states that all the time units referred in the passage are actually measured by PoS blocks. In the example part(https://www.confluxdocs.com/docs/general/conflux-basics/consensus-mechanisms/proof-of-stake/pos_overview#example), `day` is used as time unit. But it is not counted by the real world seconds but PoS blocks.
