### ISSUE TITLE
Update docusaurus to 3.0 to use it's new features

### ISSUE THREAD

**Issue by Pana** [Conflux-Chain/conflux-documentation#250]
**Describe the feature or improvement 描述新特性或改进**
https://docusaurus.io/blog/releases/3.0

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by darwintree** [comment]
The docusaurus 3.0 might result in large scale refactor due to the renewal of the markdown engine. It should be considered that if it worths it

**Comment by darwintree** [comment]
A test build for docusaurus v3 is done and the migration is much easier than expected. Will do the migration after the project structure become stable
