### ISSUE TITLE
Add conflux eSpace in wagmi's chain list documentation

### ISSUE THREAD

**Issue by Pana** [Conflux-Chain/conflux-documentation#279]
**Describe the feature or improvement 描述新特性或改进**
Conflux eSpace is already add to viem code, but the doc is not update, it's better add espace in the doc list 

https://wagmi.sh/core/chains

**Comment by darwintree** [comment]
It was already available by using

```ts
import { createPublicClient, http } from 'viem'
import { confluxESpace } from 'viem/chains'

const client = createPublicClient({
  chain: confluxESpace,
  transport: http(),
})
```

**Comment by darwintree** [comment]
A new PR is requested to add testnet
https://github.com/wevm/viem/pull/1547
