### ISSUE TITLE
Form to create issues easily

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#299]
### Describe the feature or improvement 描述新特性或改进

Create a form 

### Contribution Confirmation

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
https://forms.office.com/r/pKVBywZwLY

**Comment by darwintree** [comment]
Furthur work should be done to integrate Microsoft workflow & Github issues
