### ISSUE TITLE
Introduce LLM-based Search

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#315]
### Describe the feature or improvement 描述新特性或改进

引入基于大模型的问答用于搜索

### Contribution Confirmation

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by darwintree** [comment]
The priority tag is attached to this issue because algolia will fail to provide suppport for specific string search in most cases. For example: `deferred pool`

**Comment by jackleeio** [comment]
Is this feature under development? If not, I will try to add this feature, how can I assign this issue to me with dework?

**Comment by darwintree** [comment]
> Is this feature under development? If not, I will try to add this feature, how can I assign this issue to me with dework?

We are trying to integrate Myshell into our documents but currently the progress stuck due to some reason and we cannot estimate when the integration could be done. **It is welcome for you to try some solution but I would remind you that there is *great possibility* your work would not be merged if there would be i18n or hallucination issues or quality issues (these are questions we've ever encountered).**

As for Dework, it seems currently Dework itself is under some question and the integration is not working. 

If you still would love to accomplish this task, let me know.

**Comment by jackleeio** [comment]
Well, it seems that this function is not too urgent and will take a lot of time.

In addition, before the dework is integrated, will all PRs not be merged?

**Comment by darwintree** [comment]
> Well, it seems that this function is not too urgent and will take a lot of time.
> 
> In addition, before the dework is integrated, will all PRs not be merged?

We prefer not to merge the external PRs before dework is fixed. We will let you know if the problem is resolved

**Comment by jackleeio** [comment]
> We prefer not to merge the external PRs before dework is fixed. We will let you know if the problem is resolved

Not fixed yet? 🤣 A week has passed

**Comment by darwintree** [comment]
> > We prefer not to merge the external PRs before dework is fixed. We will let you know if the problem is resolved
> 
> Not fixed yet? 🤣 A week has passed

Already responded in #484 , and it is still not recovered after a week passes. We're sorry to find that and if you check the Dework discord chat history you will notice that other developers are encountered with the same issue in the previous week
