### ISSUE TITLE
Explain how espace works

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#322]
### Describe the feature or improvement 描述新特性或改进

Currently we're lacking details describing how espace works, including:
1. why espace's throughtput is 1/10 of the total chain
2. what's the relationship of espace blocks and core space epochs
3. If reorg took place, what will happen in espace
4. how tx.origin works in espace

...

### Contribution Confirmation

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by Pana** [comment]
https://medium.com/conflux-network/conflux-espace-a-high-level-overview-cdca29bc422a 
this doc explain the point 2, I will add it to espace overview
