### ISSUE TITLE
Event Tracking for documentation deployments

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#325]
### Describe the feature or improvement 描述新特性或改进

Track user events to view the most frequency visited pages and user behaviours

### Contribution Confirmation

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
We are already getting the following information from algolia search engine. Does this help?

![image](https://github.com/Conflux-Chain/conflux-documentation/assets/111755752/fe7a87b1-0c67-462f-8019-2455e569af3e)

![image](https://github.com/Conflux-Chain/conflux-documentation/assets/111755752/7fdabaf9-1dc0-4d3a-9ff6-3ea5602ff1e2)

**Comment by darwintree** [comment]
Yes, I think this issue can be closed
