### ISSUE TITLE
Discord link provided on coinmarketcap is invalid

### ISSUE THREAD

**Issue by eirikhanasand** [Conflux-Chain/conflux-documentation#330]
### Describe the issue 描述问题

On coinmarketcap, the link https://discord.com/invite/aCZkf2C has expired or is invalid, preventing users from joining your Discord. 

### Optional: Suggested solution 如何解决

Provide a new invite link and update it on coinmarketcap.

### Confirmation

- [ ] I'd be willing to fix this issue myself. 我将自己修复这个问题。

**Comment by darwintree** [comment]
Thank for your feedback! We'll check it

**Comment by 0xn1c0** [comment]
It's fixed
