### ISSUE TITLE
FAQ Index page

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#333]
### Describe the feature or improvement 描述新特性或改进

Currently, there are FAQs located at general/faq but also in some specific pages, for example, node faqs in general/run-a-node/nodes-faqs. We should add a page collecting information of faqs in different pages

### Contribution Confirmation

- [x] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
Page created in this PR: https://github.com/Conflux-Chain/conflux-documentation/pull/343
