### ISSUE TITLE
Create Graphs Illustrating Spaces Relationship

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#354]
### Describe the feature or improvement 描述新特性或改进

Create several graphs illustrating spaces relationship, mainly including:

- what is the relationship of logically spaces and phisical blocks?
- The relationship of core space and espace: how do they communicate, and how cfx is retrieved from espace

NOTE: it should be considered if furthur new spaces would be added to 

### Contribution Confirmation

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
Would something like this work?
![2](https://github.com/Conflux-Chain/conflux-documentation/assets/111755752/2abcf4b7-6bd7-4cb1-bbf0-a214e7ceb1d3)

**Comment by darwintree** [comment]
This is a good example. We need graphs for general infrastructure as well as technical details
