### ISSUE TITLE
Fix docusaurus broken links

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#357]
### Describe the issue 描述问题

Multiple links are currently broken

### Confirmation

- [ ] I'd be willing to fix this issue myself. 我将自己修复这个问题。

**Comment by 0xn1c0** [comment]
Are there still any broken links that need to be fixed?

**Comment by darwintree** [comment]
I've already fixed some of them. You can check it by manually building the page and the broken links will be displayed in the build output

**Comment by 0xn1c0** [comment]
https://github.com/Conflux-Chain/conflux-documentation/pull/470
