### ISSUE TITLE
Create Graphs for Initial CFX Distribution

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#359]
### Describe the feature or improvement 描述新特性或改进

Create Graphs for Initial CFX Distribution

### Optional: Affected page(s) or section(s) 受影响的页面

docs/general/conflux-basics/economics

### Contribution Confirmation

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
https://github.com/Conflux-Chain/conflux-documentation/pull/470
