### ISSUE TITLE
New Glossaries Needed

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#371]
### Describe the feature or improvement 描述新特性或改进

Glossaries is advised to add to the glossary page

- pivot chain
- finalization
- mined

https://confluxnetwork.org/files/Conflux_Protocol_Specification.pdf

### Contribution Confirmation

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by 0xn1c0** [comment]
https://github.com/Conflux-Chain/conflux-documentation/pull/471
