### ISSUE TITLE
Add Product

### ISSUE THREAD

**Issue by jcbm123143** [Conflux-Chain/conflux-documentation#374]
### Describe the feature or improvement 描述新特性或改进

**Add Product** I suggest add product so visitors or users can see what product confluxnetwork has like NFT and others.

### Optional: Why is this feature or improvement important? 为什么需要这个新特性或改进？

To immediately see what products confluxnetwork has and this is a great help to future visitors or users to make it easier to find products that confluxnetwork has like nft and others.

### Contribution Confirmation

- [X] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by darwintree** [comment]
Some links could help you to create pull request
https://123cfx.com/
https://www.confluxnetwork.org/zh/ecosystem

**Comment by 0xn1c0** [comment]
I have created an Ecosystem Page on this PR: https://github.com/Conflux-Chain/conflux-documentation/pull/392

More projects can be added to that page
