### ISSUE TITLE
Homepage localization

### ISSUE THREAD

**Issue by clangofthebell** [Conflux-Chain/conflux-documentation#375]
### Describe the issue 描述问题

![image](https://github.com/Conflux-Chain/conflux-documentation/assets/22148449/9278938a-e387-453b-9026-458468402093)

I tried to change the language to Chinese but it is still written in English.

### Confirmation

- [ ] I'd be willing to fix this issue myself. 我将自己修复这个问题。

**Comment by darwintree** [comment]
This is a known issue as currently only the contents under docs/ folder supports localization. We have the plan to localize the homepage but not at the moment
