### ISSUE TITLE
User Guide (Configure your wallet)

### ISSUE THREAD

**Issue by jcbm123143** [Conflux-Chain/conflux-documentation#376]
### Describe the feature or improvement 描述新特性或改进

**User Guide Add Configure your wallet** 
I suggest in the **User Guide** to put **Configure your wallet** because there are still many crypto users who don't know how to use confluxnetwork.

### Optional: Why is this feature or improvement important? 为什么需要这个新特性或改进？

To help crypto or newbies in conflux when setting up their wallet on metamask.

### Contribution Confirmation

- [ ] I'd be willing to contribute this feature myself. 我将自己实现这个feature

**Comment by darwintree** [comment]
There is already articles telling users how to install or configure their wallets. For example, https://www.confluxdocs.com/docs/general/tutorials/wallets/, https://www.confluxdocs.com/docs/core/getting-started/installing-a-wallet and https://www.confluxdocs.com/docs/espace/UserGuide. Why do you think this is not enough and what else content are you desiring?
