### ISSUE TITLE
误操作将资产充值到另外一条链的地址

### ISSUE THREAD

**Issue by 13928409629** [Conflux-Chain/conflux-documentation#409]
将conflux espace网络的USDT 充值到币安平台BSC网络地址中，导致USDT无法到账，而conflux espace钱包地址又少了的问题，能不能把没到账的自动退回呢？

钱包地址：0x60348097C21522B4dD1b9b2c85B52BeD4f563359

交易详情：https://evm.confluxscan.net/address/0x35b0d0d7d19756d9b6ff8399721128b650a507ae?tab=transfers-ERC20

可以帮忙找回下吗？

**Comment by darwintree** [comment]
这个问题应该需要联系BSC平台
