### ISSUE TITLE
add "How do I pay less gas?" in general/conflux-basics/gas

### ISSUE THREAD

**Issue by jackleeio** [Conflux-Chain/conflux-documentation#451]
### Describe the feature or improvement 描述新特性或改进

add "How do I pay less gas?" in general/conflux-basics/gas page

### Optional: Affected page(s) or section(s) 受影响的页面

https://www.confluxdocs.com/docs/general/conflux-basics/gas

### Optional: Why is this feature or improvement important? 为什么需要这个新特性或改进？

Add some new content to the gas explanation part to make the document more comprehensive and provide a better experience for new users

### Contribution Confirmation

- [X] I'd be willing to contribute this feature myself within 2 months. 我将在两个月内自己实现这个feature

**Comment by darwintree** [comment]
Thank you for your issue! And looking forward to your pull request!
