### ISSUE TITLE
Add the definition of EVM in the Glossary chapter

### ISSUE THREAD

**Issue by jackleeio** [Conflux-Chain/conflux-documentation#469]
### Describe the feature or improvement 描述新特性或改进

Add the definition of EVM in the Glossary chapter

### Optional: Affected page(s) or section(s) 受影响的页面

https://www.confluxdocs.com/docs/general/conflux-basics/glossary

### Contribution Confirmation

- [X] I'd be willing to contribute this feature myself within 2 months. 我将在两个月内自己实现这个feature

**Comment by 0xn1c0** [comment]
Assigned this one to myself as I'm already working on this other issue https://github.com/Conflux-Chain/conflux-documentation/issues/371

**Comment by 0xn1c0** [comment]
https://github.com/Conflux-Chain/conflux-documentation/pull/471
