### ISSUE TITLE
Add a tutorial on how to deploy a dedicated IPFS gateway

### ISSUE THREAD

**Issue by jackleeio** [Conflux-Chain/conflux-documentation#475]
### Describe the feature or improvement 描述新特性或改进

Add a tutorial on how to deploy a dedicated IPFS gateway

### Optional: Affected page(s) or section(s) 受影响的页面

https://doc.confluxnetwork.org/docs/category/nfts

### Optional: Why is this feature or improvement important? 为什么需要这个新特性或改进？

Make documentation more comprehensive and developer-friendly

### Optional: Implementation ideas 如何实现

Add a tutorial for deploying an ipfs private gateway in the NFT section
<img width="964" alt="Screenshot 2024-03-20 at 15 51 21" src="https://github.com/Conflux-Chain/conflux-documentation/assets/20477587/7702c97d-69a0-4dcd-8a5b-a9b35b08d0d4">

### Contribution Confirmation

- [X] I'd be willing to contribute this feature myself within 2 months. 我将在两个月内自己实现这个feature

**Comment by darwintree** [comment]
I'm kind of against this issue as the IPFS is not the original desired article for this part. This part is designed to put nft-related articles and we first noticed that we need something relating to static assets and so there are 2 articles relating to ipfs. We would rather put a link in IPFS overview relating to IPFS deployment but not create a new page
