### ISSUE TITLE
Refactor the 'How to deploy smart contracts' section of the eSpace tutorial.

### ISSUE THREAD

**Issue by jackleeio** [Conflux-Chain/conflux-documentation#477]
### Describe the feature or improvement 描述新特性或改进

It would be more effective to restructure this section under the heading 'Smart Contracts,' encompassing not only the deployment of contracts but also their development. This would allow for a detailed introduction of how to utilize tools such as Hardhat, Foundry, and Thirdweb, with distinct subsections dedicated to each platform's specific usage.

<img width="1257" alt="Screenshot 2024-03-20 at 16 08 39" src="https://github.com/Conflux-Chain/conflux-documentation/assets/20477587/01d7c78e-076b-4cb6-b173-55435b717a8f">

### Optional: Affected page(s) or section(s) 受影响的页面

https://doc.confluxnetwork.org/docs/espace/tutorials/deployContract/hardhatAndFoundry

### Optional: Why is this feature or improvement important? 为什么需要这个新特性或改进？

Improvements such as this will be crucial for educating thousands of newcomers about blockchain development through Conflux in the future.

### Contribution Confirmation

- [X] I'd be willing to contribute this feature myself within 2 months. 我将在两个月内自己实现这个feature

**Comment by darwintree** [comment]
Would you explain the desired structure from your point of view? I do think we need more tutorials for contract developer but it might not be a good idea to add that detailed tutorial for every dev tool

**Comment by jackleeio** [comment]
It’s okay to put smart contract development tutorials (mainly using solidity to write contracts) in General/build, but tools like Foundry don’t actually support coreSpace. I think detailed tutorials on how to develop contracts through these tools should also be written. Instead of just briefly introducing how to deploy.


Imagine you are a new web3 developer. The reality is that these contents must be too crude for you, too little and cannot solve actual problems. You also need to collect information elsewhere, which leads to a bad development experience. But if you are an experienced developer, and if you know that conflux espace is compatible with evm, these contents are dispensable for you.


But most of the time, your documentation, especially the tutorial part, is aimed at junior developers. Imagine a group of web2 developers coming into contact with the blockchain through conflux for the first time and wanting to do something on conflux, they won’t even know what hardhat and foundry are. But if you compare it to Ethereum, they have many tutorials for beginners, which is why many new developers from web2 are attracted to Ethereum.


I think in the future you want to attract not only developers from other chains, but also new developers from web2.

<img width="1048" alt="image" src="https://github.com/Conflux-Chain/conflux-documentation/assets/20477587/284d6ac0-43de-4d7f-aa3b-1945416fec0f">



<img width="1051" alt="image" src="https://github.com/Conflux-Chain/conflux-documentation/assets/20477587/73eb091d-0f72-4669-83b9-0cf90cd63b5e">
