### ISSUE TITLE
Deprecate Dework as Contribution Tool

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#484]
### Describe the feature or improvement 描述新特性或改进

It seems that Dework is down and not under maintainance. We'd choose other tools to record contribution statistics

### Contribution Confirmation

- [X] I'd be willing to contribute this feature myself within 2 months. 我将在两个月内自己实现这个feature

**Comment by jackleeio** [comment]
In fact, there are not that many real community contributors. All these contributions can be counted manually🤣 It’s not yet to the point of using tools.

**Comment by jackleeio** [comment]
However, if the submitted PR is not merged for a long time, it will lead to a very bad experience. Contributors are more concerned about substantial changes in the results of their contributions.

**Comment by darwintree** [comment]
> However, if the submitted PR is not merged for a long time, it will lead to a very bad experience. Contributors are more concerned about substantial changes in the results of their contributions.

Sorry for the bad experience brought to you. 

As we've decided to use Dework in the plan(you can check from the repo history), we are trying to contact dework to see if the service would recover to make everything work. However, as the dework still went down (You can see in the dework discord server) and we did not receive any response for a whole week, we decided to turn to other other tools. And just as you mentioned, we are doing things manually so we do not intend to use complex tools currently, I think the final options would be chosen from google docs, notion, or simply excel.

Sorry again for your bad experience. And as dework is deprecated, the review and merge process will go on normally now. We'll let you know the progress of your pull requests.

**Comment by jackleeio** [comment]
Thanks for your attention to this matter. I've understood the challenges with Dework and appreciate the move towards alternative tools for project management. 

I'm excited to see the progress on my pull requests and hope these efforts will contribute to making Conflux even better.
