### ISSUE TITLE
Check the front header display problem

### ISSUE THREAD

**Issue by lululu00** [Conflux-Chain/conflux-documentation#492]
### Describe the issue 描述问题

Please check the front header display problem.
<img width="362" alt="image" src="https://github.com/Conflux-Chain/conflux-documentation/assets/161792123/52306324-ce66-4c2c-a799-bfc9afdfeed0">

### Optional: Affected page(s) or section(s) 受影响的页面

https://www.confluxdocs.com/zh-CN/docs/general/hardforks/v2.0

### Confirmation

- [ ] I'd be willing to fix this issue myself within 2 months. 我将在两个月内自己修复这个问题。

**Comment by darwintree** [comment]
Already mentioned in #488
