### ISSUE TITLE
Trailing slash issue

### ISSUE THREAD

**Issue by lululu00** [Conflux-Chain/conflux-documentation#522]
### Describe the issue 描述问题

When I visit page(https://doc.confluxnetwork.org/docs/core/Overview/),and want to go to other pages,I find some links are broken.
(Actually almost all links in the end of the page are broken.)

broken links：
https://doc.confluxnetwork.org/docs/core/Overview/getting-started/
https://doc.confluxnetwork.org/docs/core/Overview/core-developer-quickstart
https://doc.confluxnetwork.org/docs/core/Overview/build/quickstart-for-eth-devs
https://doc.confluxnetwork.org/docs/core/Overview/tutorials/js-conflux-sdk
https://doc.confluxnetwork.org/docs/core/Overview/tutorials/hardhat-conflux-plugin
https://doc.confluxnetwork.org/docs/core/Overview/tutorials/chainide
https://doc.confluxnetwork.org/docs/core/Overview/tutorials/how-to-sponsor-contract
https://doc.confluxnetwork.org/docs/core/Overview/tutorials/nft-tutorial
https://doc.confluxnetwork.org/docs/core/Overview/core-space-basics/addresses
https://doc.confluxnetwork.org/docs/core/Overview/core-space-basics/accounts
https://doc.confluxnetwork.org/docs/core/core-space-basics/transactions/overview
https://doc.confluxnetwork.org/docs/core/Overview/core-space-basics/storage
https://doc.confluxnetwork.org/docs/core/Overview/core-space-basics/vm-difference
https://doc.confluxnetwork.org/docs/core/Overview/core-space-basics/internal-contracts/
https://doc.confluxnetwork.org/docs/core/Overview/core-space-basics/sponsor-mechanism
https://faucet.confluxnetwork.org/
https://doc.confluxnetwork.org/docs/core/general/run-a-node/Overview
https://doc.confluxnetwork.org/docs/core/Overview/build/json-rpc/

![Screenshot_20240411_191003_com android chrome](https://github.com/Conflux-Chain/conflux-documentation/assets/161792123/31fc9b23-9a27-4ed2-a26c-51a8ae98a72d)

### Optional: Affected page(s) or section(s) 受影响的页面

https://doc.confluxnetwork.org/docs/core/Overview/

### Confirmation

- [ ] I'd be willing to fix this issue myself within 2 months. 我将在两个月内自己修复这个问题。

**Comment by darwintree** [comment]
Thank you for feedback. Will fix ASAP

**Comment by darwintree** [comment]
This seems to be an error caused by deployments. Would you check if certain problem occurs for the domain [confluxdocs.com](https://www.confluxdocs.com/docs/core/Overview)?

**Comment by lululu00** [comment]
> ~This seems to be an error caused by deployments. Would you check if certain problem occurs for the domain [confluxdocs.com](https://www.confluxdocs.com/docs/core/Overview)?~
> 
> Confirmed that this issue is occured because you are visiting https://doc.confluxnetwork.org/docs/core/Overview/ but not https://doc.confluxnetwork.org/docs/core/Overview. Will dig into solutions

It seems that problems also exist in https://doc.confluxnetwork.org/docs/core/Overview

**Comment by darwintree** [comment]
> > ~This seems to be an error caused by deployments. Would you check if certain problem occurs for the domain [confluxdocs.com](https://www.confluxdocs.com/docs/core/Overview)?~
> > Confirmed that this issue is occured because you are visiting https://doc.confluxnetwork.org/docs/core/Overview/ but not https://doc.confluxnetwork.org/docs/core/Overview. Will dig into solutions
> 
> It seems that problems also exist in https://doc.confluxnetwork.org/docs/core/Overview

This is actually an issue due to trailing slash resolution

**Comment by darwintree** [comment]
@lululu00  Would you check if this still exist for confluxdocs.com ? For example, https://www.confluxdocs.com/docs/core/Overview/

**Comment by lululu00** [comment]
> @lululu00 Would you check if this still exist for confluxdocs.com ? For example, https://www.confluxdocs.com/docs/core/Overview/

solved，thank you
