### ISSUE TITLE
Add WalletConnect Project Creation Guide

### ISSUE THREAD

**Issue by darwintree** [Conflux-Chain/conflux-documentation#534]
### Describe the feature or improvement 描述新特性或改进

Developers need to get projectid to use WalletConnect. An individual guide is suggested to add for simple WalletConnect project creation

### Contribution Confirmation

- [ ] I'd be willing to contribute this feature myself within 2 months. 我将在两个月内自己实现这个feature

**Comment by darwintree** [comment]
@jackleeio would know if you are interested in this issue. Or I'll add it

**Comment by jackleeio** [comment]
Yes, I'll add it this weekend.
