### ISSUE TITLE
Some uncertain questions

### ISSUE THREAD

**Issue by jackleeio** [Conflux-Chain/conflux-documentation#584]
### Describe the feature or improvement 描述新特性或改进

For the [complete tutorial on NFT](https://www.confluxdocs.com/docs/core/tutorials/nft-tutorials/crc721), I am not sure that the eSpace part also needs to create related tutorials. In addition, the content of the issue #583 also applies to eSpace. I am not sure whether it is appropriate to put it in coreSpace? But I haven't found a more suitable place. For new users who don't know much about Conflux, if they want to do similar things in eSpace, but find that these contents are only available in coreSpace, they may be a little confused.

### Contribution Confirmation

- [ ] I'd be willing to contribute this feature myself within 2 months. 我将在两个月内自己实现这个feature

**Comment by darwintree** [comment]
Yes, you are right, situations are there that simlilar contents is needed for different spaces. And that is why the folder [templates](https://github.com/Conflux-Chain/conflux-documentation/tree/main/docs/templates) is created.

As for your specific question, here are my suggestions
1. Create content in general folder if the content is more of general knowledge but not relating to chain-specific tools. 
2. If `1` is not applicable, try employing the template to create article for different spaces, this would benefit for maintainance and translation.
3. If `2` would bring about too much extra effort, create content for different folder independently
