### ISSUE TITLE
Link in index page not work anymore

### ISSUE THREAD

**Issue by wongzigii** [Conflux-Chain/conflux-documentation#686]
### Describe the issue 描述问题

<img width="1560" alt="image" src="https://github.com/user-attachments/assets/50a2430e-0957-456b-b74e-ef0df66fa837">

https://doc.confluxnetwork.org/docs/category/mining--staking 
the link not work anymore and will redirect to 404 page

### Optional: Affected page(s) or section(s) 受影响的页面

https://doc.confluxnetwork.org/zh-CN

### Confirmation

- [ ] I'd be willing to fix this issue myself within 2 months. 我将在两个月内自己修复这个问题。

**Comment by darwintree** [comment]
It seems this is a inpage navigating error and a workaround is to open the link in another page. We'll investigate it

**Comment by 0xffffb** [comment]
@darwintree  I want to contributor this.
