### ISSUE TITLE
Cookbook button doesn’t display well

### ISSUE THREAD

**Issue by jackleeio** [Conflux-Chain/conflux-documentation#701]
### Describe the issue 描述问题

<img width="601" alt="image" src="https://github.com/user-attachments/assets/98a9c946-b86d-4ccb-930d-ff8a17041463">

Cookbook button doesn’t display well when selecting text

<img width="720" alt="image" src="https://github.com/user-attachments/assets/72ee3206-3e79-43a8-a0d3-707101227b76">

### Confirmation

- [X] I'd be willing to fix this issue myself within 2 months. 我将在两个月内自己修复这个问题。

**Comment by darwintree** [comment]
This is a feature of cookbook. When you select text, you can directly ask cookbook about the selected context

**Comment by jackleeio** [comment]
I know, but after selecting the text, the button is too close to the icon on the left，

<img width="218" alt="image" src="https://github.com/user-attachments/assets/72a70866-3c5a-43b2-95c1-bf5eeef659a3">

<img width="225" alt="image" src="https://github.com/user-attachments/assets/3246cd09-3700-4c87-9c85-196b05c4df61">

**Comment by darwintree** [comment]
> I know, but after selecting the text, the button is too close to the icon on the left，
> 
> <img alt="image" width="218" src="https://private-user-images.githubusercontent.com/20477587/359053001-72a70866-3c5a-43b2-95c1-bf5eeef659a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMTY1MDcsIm5iZiI6MTcyNDExNjIwNywicGF0aCI6Ii8yMDQ3NzU4Ny8zNTkwNTMwMDEtNzJhNzA4NjYtM2M1YS00M2IyLTk1YzEtYmY1ZWVlZjY1OWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAxMTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMzA1ZWY5NWY3MzMzYmUzMTIwY2ZmNWYxMGY0MzEzNTIzNjdiZGZkYjc5ZjQ1MjVhNWM2YTMxNzU2ZDZiMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nh7OH-FzAi5amXLaU9avUGvJ4f5Dvl6RYROHUj_BB-I"> <img alt="image" width="225" src="https://private-user-images.githubusercontent.com/20477587/359052799-3246cd09-3700-4c87-9c85-196b05c4df61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMTY1MDcsIm5iZiI6MTcyNDExNjIwNywicGF0aCI6Ii8yMDQ3NzU4Ny8zNTkwNTI3OTktMzI0NmNkMDktMzcwMC00Yzg3LTljODUtMTk2YjA1YzRkZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAxMTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNTU2ZWQ5YTg5NmYwMDE5NWI2ZjhlNmM2ZWYzZjU1OTI2NjljMzY3YzFlMzRkNWE5ZGU5OGRjZmUwZjVjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gZiaOp36kqNRUK2SB9u5Z1oZmFGIbWNSjOZ9KcF8Olw">

Thank you for feedback. Will first commit feedback to cookbook devs for potential fix

**Comment by darwintree** [comment]
fixed
