### ISSUE TITLE
document sidebar translate

### ISSUE THREAD

**Issue by 0xffffb** [Conflux-Chain/conflux-documentation#711]
### Describe the feature or improvement 描述新特性或改进

![image](https://github.com/user-attachments/assets/b726a4c9-ebbe-4269-9a66-0c06666e58d2)

Add translation for automatically generated sidebar

### Contribution Confirmation

- [X] I'd be willing to contribute this feature myself within 2 months. 我将在两个月内自己实现这个feature

**Comment by darwintree** [comment]
These translations can be added by creating _category_.json(yml) in corresponding folder and translated by crowdin

**Comment by darwintree** [comment]
> > These translations can be added by creating _category_.json(yml) in corresponding folder and translated by crowdin
> 
> It's different from what I thought, I'll try your said.

You can check the translated folders and you will find corresponding metadata file in the folder
