### ISSUE TITLE
一些名称错误(中文文档)

### ISSUE THREAD

**Issue by cryptosunshine** [Conflux-Chain/conflux-documentation#799]
### Describe the issue 描述问题

一些名称错误(中文文档)

### Optional: Affected page(s) or section(s) 受影响的页面

https://doc.confluxnetwork.org/zh-CN/docs/espace/build/jsonrpc-compatibility

### Optional: Suggested solution 如何解决

eth_blocknumber -> eth_blockNumber
eth_getTransactionrecipt -> eth_getTransactionReceipt
eth_getBlockBynumber -> eth_getBlockByNumber
eth_getBlockTransactionCountBynumber -> eth_getBlockTransactionCountByNumber
eth_getTransactionBylockHashAndIndex -> eth_getTransactionByBlockHashAndIndex
eth_getTransactionBylockNumberAndIndex -> eth_getTransactionByBlockNumberAndIndex

### Confirmation

- [ ] I'd be willing to fix this issue myself within 2 months. 我将在两个月内自己修复这个问题。

**Comment by darwintree** [comment]
Fixed
